# Generated by Django 2.0.6 on 2018-06-23 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('type', models.CharField(choices=[('individual_entrepreneur', 'Инидивидуальный предприниматель'), ('legal_entity', 'Юридическое лицо')], max_length=50, verbose_name='Вид')),
                ('taxation_form', models.CharField(choices=[('traditional', 'Традиционная (общая) система (режим) налогообложения'), ('simplified', 'Упрощённая система налогообложения '), ('single_tax_on_imputed_income', 'Единый налог на вменённый доход'), ('unified_agricultural_tax', 'Единый сельскохозяйственный налог'), ('patent', 'Патентная система налогообложения')], max_length=350, verbose_name='Форма налогооблажения')),
                ('provider', models.BooleanField(default=False)),
                ('client', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'конрагент',
                'verbose_name_plural': 'конрагенты',
            },
        ),
    ]
