# Generated by Django 2.0.6 on 2018-06-23 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='client',
            field=models.BooleanField(default=False, verbose_name='Клиент (?)'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='provider',
            field=models.BooleanField(default=False, verbose_name='Поставщик (?)'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='taxation_form',
            field=models.CharField(choices=[('traditional', 'Традиционная (общая) система (режим) налогообложения'), ('simplified', 'Упрощённая система налогообложения '), ('single_tax_on_imputed_income', 'Единый налог на вменённый доход'), ('unified_agricultural', 'Единый сельскохозяйственный налог'), ('patent', 'Патентная система налогообложения')], max_length=350, verbose_name='Форма налогооблажения'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='type',
            field=models.CharField(choices=[('individual_entrepreneur', 'Инидивидуальный предприниматель'), ('legal_entity', 'Юридическое лицо')], max_length=100, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Обновлено'),
        ),
    ]
