# Generated by Django 2.0.6 on 2018-06-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0002_auto_20180623_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='client',
            field=models.BooleanField(default=False, verbose_name='Клиент?'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='provider',
            field=models.BooleanField(default=False, verbose_name='Поставщик?'),
        ),
    ]
