# Generated by Django 2.0.6 on 2018-06-23 16:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contractors', '0002_auto_20180623_1619'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_type', models.CharField(choices=[('often', 'Постоянно'), ('alternately', 'Переменно')], max_length=300, verbose_name='Тип расхода')),
                ('product_price', models.FloatField(default=0, verbose_name='Стоимость')),
                ('product_number_in_pack', models.FloatField(default=1, verbose_name='Количество в упаковке')),
                ('product_weight_in_pack', models.FloatField(default=0, verbose_name='Кг в упаковке')),
                ('product_count_in_pack', models.FloatField(default=1, verbose_name='Штук в упаковке')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Обновлено')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.Contractor', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name_plural': 'записи расходов',
                'verbose_name': 'запись расходов',
            },
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'статьи расходов',
                'verbose_name': 'статья расходов',
            },
        ),
        migrations.CreateModel(
            name='ExpenseItemGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'группы статей расходов',
                'verbose_name': 'группа статей расходов',
            },
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.ExpenseItemGroup', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='expense',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.ExpenseItem', verbose_name='Статья расходов'),
        ),
        migrations.AddField(
            model_name='expense',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Продукт'),
        ),
    ]
