# Generated by Django 2.0.6 on 2018-06-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20180623_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='products_total_price',
            field=models.FloatField(default=0, verbose_name='Общая стоимость'),
        ),
    ]
