# Generated by Django 2.0.6 on 2018-06-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_auto_20180623_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='products_count_in_pack',
            field=models.FloatField(blank=True, default=1, null=True, verbose_name='Штук в упаковке'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='products_number_in_pack',
            field=models.FloatField(blank=True, default=1, null=True, verbose_name='Количество в упаковке'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='products_weight_in_pack',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Кг в упаковке'),
        ),
    ]
