# Generated by Django 2.0.6 on 2018-06-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_auto_20180623_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='products_total_price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Общая стоимость'),
        ),
    ]
