# Generated by Django 2.0.6 on 2018-06-23 16:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('weight', models.FloatField(blank=True, default=0, null=True, verbose_name='Вес')),
                ('length', models.FloatField(blank=True, default=0, null=True, verbose_name='Длина')),
                ('width', models.FloatField(blank=True, default=0, null=True, verbose_name='Ширина')),
                ('height', models.FloatField(blank=True, default=0, null=True, verbose_name='Высота')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name_plural': 'продукты',
                'verbose_name': 'продукт',
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name_plural': 'группы продуктов',
                'verbose_name': 'группа продуктов',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductGroup', verbose_name='Группа'),
        ),
    ]
