# Generated by Django 2.0.6 on 2018-06-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='product_number',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Количество протуктов'),
        ),
        migrations.AlterField(
            model_name='income',
            name='product_price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Стоимость за единицу'),
        ),
        migrations.AlterField(
            model_name='income',
            name='total_sum',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Общая стоимость'),
        ),
    ]
